version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dos2unix...
      - yum install -y dos2unix

  pre_build:
    commands:
      - echo Cloning repository...
      - git clone https://github.com/SaiRamya15/gradle-githubactions.git
      - cd gradle-githubactions
      - echo Fixing gradlew line endings and permissions...
      - dos2unix gradlew
      - chmod +x gradlew

  build:
    commands:
      - echo Building the project with Gradle...
      - ./gradlew clean build
      - echo Running the JAR...
      - java -jar build/libs/gradle-githubactions-demo-17.0.5.jar

artifacts:
  files:
    - gradle-githubactions/build/libs/*.jar
