//version: 0.2

//phases:
  //install:
    //runtime-versions:
      //java: corretto17
version: 0.2
phases:
  install:
    commands:
      - chmod +x gradlew  # Make sure gradlew is executable
  build:
    commands:
      - ./gradlew clean build  # Clean build before executing


  pre_build:
    commands:
      - echo Cloning repository...
      - git clone https://github.com/SaiRamya15/gradle-githubactions.git

  build:
    commands:
      - echo Building the project with Gradle...
      - cd gradle-githubactions
      - chmod +x gradlew
      - ./gradlew clean build
      - echo Running the JAR file...
      - java -jar build/libs/gradle-githubactions-demo-1.0-SNAPSHOT-17.0.5.jar

artifacts:
  files:
    - gradle-githubactions/build/libs/*.jar
