name: Build Gradle Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permissions for Gradle wrapper
        run: chmod +x gradlew

      - name: Build project and generate JAR
        run: ./gradlew clean build

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: gradle-app-jar
          path: build/libs/*.jar
